name: Notify Discord on Push

on: 
  push:
    branches:
      - '*'  # Surveiller toutes les branches

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
    - name: Send Discord notification
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_ACTOR: ${{ github.actor }}
      run: |
        curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"New commit pushed by $GITHUB_ACTOR in $GITHUB_REPOSITORY on branch ${{ github.ref_name }}: ${{ github.event.head_commit.message }}\"}" $DISCORD_WEBHOOK_URL
